FROM eclipse-temurin:21
RUN mkdir /opt/app
COPY wordTransformer-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/app
CMD ["java", "-jar", "/opt/app/wordTransformer-1.0-SNAPSHOT-jar-with-dependencies.jar"]
